### GET request to example server
GET https://v3.football.api-sports.io/status
x-apisports-key: f7b1392fae222d5f75cc58473a670453
###

### GET requests to get a single player
GET https://v3.football.api-sports.io/players/profiles
x-Apisports-Key: f7b1392fae222d5f75cc58473a670453


### GET request to get squads
GET https://v3.football.api-sports.io/players/squads?team=33
x-Apisports-Key: f7b1392fae222d5f75cc58473a670453


### GET a single plyer
GET http://localhost:8080/players/profile
x-Apisports-Key: f7b1392fae222d5f75cc58473a670453
